services:
  # ================================================================
  #  Web Service — API Spring Boot
  # ================================================================
  - type: web
    name: bank-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: bank-api-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bank-api-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: bank-api-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bank-api-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bank-api-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
  # ================================================================
  #  Base de données PostgreSQL géré par Render
  # ================================================================
databases:
  - name: bank-api-db
    plan: free
    databaseName: bankdb
    user: bankuser
